ROOT_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

TARGET = bw_example_fx_notch

C_SOURCES += ${ROOT_DIR}/../src/bw_example_fx_notch.c

include ${ROOT_DIR}/../../common/daisy-seed/daisy-seed.mk
