ROOT_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

TARGET = bw_example_fxpp_dist

CPP_SOURCES_EXTRA = ${ROOT_DIR}/../src/bw_example_fxpp_dist.cpp

include ${ROOT_DIR}/../../common/daisy-seed/daisy-seed.mk
