ROOT_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

TARGET = bw_example_fxpp_noise_gate

CPP_SOURCES_EXTRA = ${ROOT_DIR}/../src/bw_example_fxpp_noise_gate.cpp

include ${ROOT_DIR}/../../common/daisy-seed/daisy-seed.mk
