ROOT_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

TARGET = bw_example_fx_flanger

C_SOURCES += ${ROOT_DIR}/../src/bw_example_fx_flanger.c

include ${ROOT_DIR}/../../common/daisy-seed/daisy-seed.mk
