ROOT_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

TARGET = bw_example_synthpp_poly

CPP_SOURCES_EXTRA = ${ROOT_DIR}/../src/bw_example_synthpp_poly.cpp

SYNTH := yes

include ${ROOT_DIR}/../../common/daisy-seed/daisy-seed.mk
