ROOT_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

TARGET = bw_example_fx_wah
CPP_SOURCES += ${ROOT_DIR}/../src/bw_example_fx_wah.c

include ${ROOT_DIR}/../../common/daisy-seed/daisy-seed.mk
